### PR TITLE
Adding required field origin_country_code

### PR DESCRIPTION
**Pull request by rewake**
Wish recently added a new required field, "Origin Country". This commit brings WishTracker model up to spec with requirements. 

For more information, see: https://merchantfaq.wish.com/hc/en-us/articles/360011032634

### CODE REVIEW

**Comment by andreisusanu** [comment]
Looks good, thanks!

**Comment by tvi** [comment]
Thank you for contributing to our API SDK, I will try to get somebody to review and merge in your PR.

**Comment by rewake** [comment]
Hey guys! Any updates on this PR? Wish API is now throwing errors due to this required field missing.

**Comment by tvi** [comment]
Thank you again for contributing.

We had internal discussion and found out that this library is deprecated and needs to be reworked, but in the mean time I am happy to accept your changes.

**Comment by rewake** [comment]
Ah ok awesome - thanks Tomas! Looking forward to the new version of the library.

**Pull request merged**
